### ISSUE TITLE
Dynamic segments include extention

### ISSUE THREAD

**Issue by amiel** [tildeio/route-recognizer#125] opened 2016-12-23 00:28 UTC
When defining a dynamic route with an extension, such as `/users/:id.json`, route-recognizer considers `:id.json` a dynamic segment, when it should consider `:id` the dynamic segment.

When resolving the aforementioned example (`/users/:id.json`), with `/users/1.json`, the recognized params are: `"params": { "id.json": "1.json" }`. I expected them to be `"params": { "id": "1" }`.

I found this issue through `ember-cli-mirage`. While my ember app does not include extensions like this, my API does.

Here is an example twiddle demonstrating the issue: https://ember-twiddle.com/5bbd4af2a97afe54b6fe6833ad0a1758?numColumns=2&openFiles=mirage.config.js%2Cadapters.user.js

I am currently working on a PR to resolve this, but wanted to open the issue to document process, and also to double check that this is not intentional.

UPDATE: This test demonstrates my issue https://github.com/actionsprout/route-recognizer/commit/95ec725.

**Comment by nathanhammond** [comment] 2016-12-24 20:15
@amiel This is not a bug. Dynamic segments are _entire segments_. `route-recognizer` is not a generic string portion replacement library. It is used to identify the handlers for a particular route path. If you need to parse the values differently you'll need to do so at a level of abstraction higher than `route-recognizer` which will always return `1.json`.

In your case if you need to return different values for assets based upon type I would investigate sending `accept` headers to the `/users/1` endpoint.

I'm closing this issue. In the mean time we will still continue to receive notifications from any followup comments on this issue; being closed doesn't mean that we're ignoring the thread.

**Closed by nathanhammond** 2016-12-24 20:15 UTC

**Comment by amiel** [comment] 2016-12-28 18:55
@nathanhammond I'd love to discuss potential solutions to my issue.

1. The approach I was planning to take is to consider segments to be delimited by `/` or `.`, as opposed to just `/`.

    This way "Dynamic segments are _entire segments_" still holds true, and we redefine what a segment is.

    Do you think this would cause serious backward compatibility issues? I can't imagine wanting `.` as a part of a dynamic segment name, especially considering how `.` is used for object traversal in javascript.

    If you like this approach, I am happy to work on it.

2. You recommended using an endpoint without an extension, and the `accept` header.

    This would be possible, but a large project for us to change all of our endpoints, and I imagine that some people would like to use `ember-cli-mirage` to mock apis that they do not have control over.

    Kind of a side note, but I have found that relying on the `accept` header only is susceptible to [this issue](https://bugs.chromium.org/p/chromium/issues/detail?id=68096). Using an extension to distinguish between data types is the most sure way I have found to prevent that issue. Do you have any other suggestions for preventing this issue?

3. > If you need to parse the values differently you'll need to do so at a level of abstraction higher than route-recognizer

    This seems doable, but feels like a hack. Either ember-cli-mirage or Pretender would have to do some extra parsing. It ends up being a little tricker because the added extension needs to be removed from both the segment name and the segment value. And, while I don't feel that `:id.json` is a reasonable segment name, `1.json` _is_ a perfectly reasonable segment value. I just think it makes more sense to handle this at parse time as opposed to after.

    If you still think this is the best approach, I will open an issue with ember-cli-mirage and continue to persue a solution there.

Please advise :)
